name: deploy_fn3

on: 
  ["workflow_dispatch"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install packages, build, and start server
      uses: fifsky/ssh-action@master
      with:
        command: cd /$(USER)/go-quai && git pull && make go-quai && make stop && export HOST_IP=$(hostname -I | awk '{print $1}') && make run-bootnode
        host: ${{ secrets.FN3_HOST }}
        user: ${{ secrets.FN3_USER}}
        key: ${{ secrets.FN3_KEY}}